### ISSUE TITLE
Release a new version on NPM

### ISSUE THREAD

**Issue by rileyjshaw** [tobiaswright/pocket-api#31]
There have been many improvements to this library since the last publish on NPM ([v1.0.1 was published over two years ago at 2020-08-03T18:49:10.607Z](https://www.npmjs.com/package/pocket-api)).

Are you willing to publish a new version `v1.1.0`?

**Comment by rileyjshaw** [comment]
@tobiaswright just following up, any thoughts on this?

**Comment by tobiaswright** [comment]
@rileyjshaw my apologies! Yes, I'll publish to npm

**Comment by rileyjshaw** [comment]
@tobiaswright thank you! And while I’m here, https://github.com/tobiaswright/pocket-api/pull/32 is also still open 😉

**Comment by rileyjshaw** [comment]
Thanks again @tobiaswright!
